
spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://*****:3306/nanjustar?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ****  #username
    password: **** #password
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    time-zone: GMT+8

mybatis-plus:
  # mapper.xml位置
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      # 逻辑删除配置
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0